name: BeaconBeamRemoverV1
version: '1.0'
main: beaconbeamremoverv1.codfather
api-version: 1.20
authors: [ Codfather ]
description: Does what it says in the title you fucktard
website: codfather69420.org
